initial release
reason-react-native/checkbox pull request #2
Opened 2019-10-06 11:48 UTC by sgny

Here is what I pushed to the repo (and undid later).

I suppose once @tatchi's bindings are merged, we can pull documentation, etc. from this.

2019-10-11 14:36 UTC, sgny commented
I merged @tatchi's version as he had already contributed the important part. This revised PR adds documentation and brings this repo in line with the template.

However, some remaining issues are
- resolving `@reason-react-native/react-native` vs `reason-react-native`
- whether we refer to the module as `ReactNativeCheckBox` or `ReactNativeCheckbox`
- use `open ReactNative` or not

2019-10-14 10:02 UTC, MoOx requested changes
Looks good! Just a tiny thing to remove :D

2019-10-14 10:02 UTC, MoOx commented on README.md
> +---
```suggestion

```

2019-10-14 10:02 UTC, MoOx commented on README.md
> +
```suggestion
```

2019-10-14 10:08 UTC, MoOx commented
@sgny To answer you

- Use `reason-react-native` 
- I would go with "Checkbox" as it's the common spelling (even wikipedia know this)
- `open ReactNative` if that's required, it's not an issue as we are doing this everywhere.

2019-10-14 16:16 UTC, sgny commented
Will implement those

One issue, the component is address from JS as `CheckBox`. That's why I figured if we should have it spelled like that.

2019-10-16 09:08 UTC, sgny commented on README.md
> +---
implemented

2019-10-19 13:22 UTC, sgny commented
@MoOx merging this, the only open issue is the name for the module, which is fine as it is.

2019-10-19 13:22 UTC, merged